apiVersion: apps/v1
kind: Deployment
metadata:
  name: muplat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: muplat
  template:
    metadata:
      labels:
        app: muplat
    spec:
      serviceAccountName: muplat-sa
      containers:
        - name: muplat
          image: {{ printf "%s:%s" .Values.repository .Values.tag }}
          env:
            - name: CONNECTION_MODE
              value: "internal"
            - name: POSTGRES_HOST
              value: pg-cluster-rw
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "app"
            - name: POSTGRES_PASSWORD
              value: ""
            - name: DATABASE
              value: app
            - name: INIT_USER
              value: initAdmin
            - name: INIT_USER_PASSWORD
              value: "secretpassword"
            - name: JWT_LIFESPAN_MINUTES
              value: "25"
            - name: JWT_SECRET
              value: "jwtsupersecretpioakdwodi8ajd"
            - name: INGRESS_NGINX_NAMESPACE
              value: "ingress-nginx"
          ports:
          - name: http
            containerPort: 8080
